language: node_js
node_js:
- '0.10'
before_script:
- node_modules/.bin/jspm install
script: node_modules/karma/bin/karma start karma.conf.js --single-run
deploy:
  provider: npm
  email: djindjic@gmail.com
  api_key:
    secure: Hqh1qoHBUZ+DevIaM8jUsPGzaDen4golqTH3trBuRViH/e3IEbKgkhTux6jXotB2C+yTAfmqWSrAhAbfLDJ6Bl3d4mmQ0RiVVBom5UzUIbjbeki0zpOshkbpirChfAhI+ewRDowTQ0gQZrUPa1lxijNcCmQSivvXDSOAXOPN9cE=
  on:
    tags: true
    all_branches: true