language: node_js
sudo: false
node_js:
- '0.10'
before_script:
  - jspm config endpoints.github.auth $JSPM_AUTH
  - jspm install
script: node_modules/karma/bin/karma start karma.conf.js --single-run
deploy:
  provider: npm
  email: djindjic@gmail.com
  api_key:
    secure: DFrMmzPi2tGBYF8no36nYqgpWOhzg//90jhMG0twyR1JhOvY6ukN7xRfIPSLVr8J8WP4cKbkaQGD+TwXbNbJS3KP1P3rTsJ8TSVawhIh3yWQJBGLcXTkvwnyscyrPyLXWqzbiFdvbsdlVgu1oxwrGnIK3GWpsq5WmhfnZot7uyc=
  on:
    tags: true
    all_branches: true
